# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

before_script:
  - ./test/setup/setup.sh

env:
  global:
    - BUILD_DIR="$TRAVIS_BUILD_DIR"
    - SERVER_SPECIFIC_TESTS="test/tests.js"

git:
  depth: 10

language: node_js

matrix:
  include:

    # Test for Apache 2.2.x
    - env:
        - APACHE_VERSION="2.2.x"
      node_js: "0.10"
      script:
        - sudo service apache2 restart
        - npm test

    # Test for Apache 2.4.x
    - env:
        - APACHE_VERSION="2.4.x"
      node_js: "0.10"
      script:
        - sudo /usr/local/apache2/bin/apachectl start
        - npm test
